source env/python/bin/activate

export UCOMP_DEVROOT=~/work/ucomp
export PYTHONDONTWRITEBYTECODE=1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$UCOMP_DEVROOT/vm/build
export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:$UCOMP_DEVROOT/vm/build
